name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: everyone
          POSTGRES_DB: postgres

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.2'
        env: GOPROXY=https://proxy.golang.org

    - name: Test
      run: go test -v -dsn="postgres://postgres:everyone@localhost:5432/postgres?sslmode=disable"
