name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        postgres-version: [15, 14, 13, 12, 11]
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: everyone
          POSTGRES_DB: postgres

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        env: GOPROXY=https://proxy.golang.org

    - name: Test
      run: go test -short -v -dsn="postgres://postgres:everyone@localhost:5432/postgres?sslmode=disable"
